#!/bin/bash

## A script to install Funtoo Linux on a computer.

####---------------------------------------------####
echo We will now start installing Funtoo Linux on this computer!

echo We will start by partitioning the hard disk.
cfdisk

echo Now, we will create the filesystems.
echo Please enter the root partition. Eg. /dev/sda?
read rootpartition
mkfs.jfs $rootpartition
# echo Please enter the swap partition. Eg. /dev/sda?
# read swap-partition
# mkswap $swap-partition
# swapon $swap-partition

echo It is time to mount the filesystems.
mkdir /mnt/funtoo
mount $rootpartition /mnt/funtoo

cd /mnt/funtoo
echo Now, we will download the stage 3 file.
wget http://ftp.heanet.ie/mirrors/funtoo/funtoo-current/x86-64bit/corei7/stage3-latest.tar.xz

echo We will extract the downloaded file.
tar xJpf stage3-latest.tar.xz

echo It is time to chroot into Funtoo linux.
mount --bind /proc proc
mount --bind /dev dev
cp /etc/resolv.conf etc
env -i HOME=/root TERM=$TERM chroot . bash -l
export PS1="(chroot) $PS1"

echo Downloading the portage tree...
emerge --sync

echo Time to configure the system.
nano -w /etc/fstab
ln -sf /usr/share/zoneinfo/Asia/Kuala_Lumpur /etc/localtime
nano -w /etc/portage/make.conf 
nano -w /etc/conf.d/hwclock
eselect profile replace 7 8
nano -w /etc/conf.d/hostname

echo Time to install the kernel.
echo "sys-kernel/debian-sources binary" >> /etc/portage/package.use
emerge debian-sources

echo Installing a bootloader...
emerge boot-update
nano -w /etc/boot.conf
grub-install --no-floppy /dev/sda
boot-update

echo Configure the network...
rc-update add dhcpcd default

echo Time to set the root password.
passwd

